### ISSUE TITLE
Hi Lala

### ISSUE THREAD

**Issue by imkhalid** [shejz/car_damage_detection#1]
Hi,
 I Have Query Regarding your repo on Car Damage Detection which is quite inspiring work you have done.
 my Query is that we were trying to run this notebook but it missing car models to run, so can you provide us feedback and get back to us. my Email : khalidsaeed36@gmail.com
        Thanks 
        Khalid Saeed

**Comment by RohitRathiii** [comment]
Hey Khalid,
Did you find the models?
if yes please share it with me on rohitrathi.in@gmail.com
@shejz

**Comment by shejz** [comment]
Hello, I already sent an invitation to your email for mega file share. Please check.
